### GET 
GET http://localhost:3000/api/cards

###GET 
GET http://localhost:3000/api/cards

### POST
POST http://localhost:3000/api/cards
Content-Type: application/json

{
   "text": "What is Node.js?",
    "author": "Max Mustermann"
}

### PUT
PUT http://localhost:3000/api/cards/12
Content-Type: application/json

{
    "text": "What is MongoDBBB?",
    "author": "John Doeee",
}

### PATCH
PATCH http://localhost:3000/api/cards/46
Content-Type: application/json

{
    "text": "This is a post request"
}

### DELETE
DELETE  http://localhost:3000/api/cards/123

